out_dir: results
dataset:
  format: OGB
  name: ogbl-collab #ddi,collab
  task: link_pred
  task_type: classification
  node_encoder: false
  node_encoder_name: Atom
  edge_encoder: false
  edge_encoder_name: Bond
  transductive: false
train:
  batch_size: 1
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
  mode: pc_train
model:
  type: pc_network

  # loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 0
  layers_mp: 2
  layers_post_mp: 0
  dim_inner: 64
  layer_type: gcnconv
  stage_type: my_stack
  batchnorm: false
  act: prelu
  dropout: 0.0
  agg: mean
  normalize_adj: false
optim:
  max_epoch: 200
pc:
 use_pc: false
 update_x_at : all
 optimizer_x_fn : Adam
 optimizer_x_lr  : 0.5
 update_p_at : last
 optimizer_p_fn : Adam
 optimizer_p_lr  : 0.001
